### ISSUE TITLE
Guardian Governance should conform to the Governance Messaging standard

### ISSUE THREAD

**Issue by evan-gray** [wormhole-foundation/example-native-token-transfers#134]
>All governance VAAs follow the GovernancePacket structure.
https://github.com/wormhole-foundation/wormhole/blob/main/whitepapers/0002_governance_messaging.md

So this standard should follow it too...

https://github.com/wormhole-foundation/example-native-token-transfers/blob/934f7e07bb628957eadaea56667353f9fd7287e6/src/wormhole/Governance.sol#L43

**Comment by kcsongor** [comment]
so maybe something like
```
GovernancePacket struct {
    // Module identifier (left-padded)
    Module [32]byte == "GeneralPurposeGovernance"
    // Action index
    Action uint8 == 1
    // Chain index (0 for non-specific actions like guardian set changes)
    Chain uint16
    // Action-specific payload fields
    [...] == calldata
}
```
?

**Comment by evan-gray** [comment]
yeah where action 1 can be designated as "EVM Call" or something

**Comment by kcsongor** [comment]
makes sense to me
