### ISSUE TITLE
Add Events

### ISSUE THREAD

**Issue by nik-suri** [wormhole-foundation/example-native-token-transfers#18]
Descriptive events that get logged when various actions happen are useful for indexers and generally analyzing data on-chain.

We should add event logging throughout the codebase. For example, when:
- State gets updated (siblings, threshold, Endpoint management, etc)
- Transfers are rate-limited or queued
- Transfers are sent
- Transfers are redeemed

**Comment by kev1n-peters** [comment]
Can we add and emit an `OutboundTransferQueued` event here? https://github.com/wormhole-foundation/example-native-token-transfers/blob/3dfb8229c8ffe0b0eed5d1090f0b90b532dfdb57/src/Manager.sol#L357 There's currently no way to get the `queueSequence` given a tx hash AFAIK
