### ISSUE TITLE
evm: add production build target with via_ir=true

### ISSUE THREAD

**Issue by kcsongor** [wormhole-foundation/example-native-token-transfers#188]
The current default profile has `via_ir=false`. We should have a production profile with `via_ir=true`
https://github.com/wormhole-foundation/example-native-token-transfers/blob/e77689ee4b1ef11243574aac9319ace39c0f9a16/evm/foundry.toml#L1-L9

**Comment by RahulMaganti47** [comment]
Fixed by #190.
