### ISSUE TITLE
evm: Use 1 and 2 to represent true and false booleans

### ISSUE THREAD

**Issue by RahulMaganti47** [wormhole-foundation/example-native-token-transfers#254]
setting a value from 0 is more expensive (~20k gas) than setting a value from (1 -> N) (~5k gas). 

https://github.com/wormhole-foundation/example-native-token-transfers/blob/1470fc6071765fd7cee4b12e6214cda1ee338487/evm/src/libraries/TransceiverHelpers.sol#L4

**Comment by kcsongor** [comment]
this makes sense on a case by case basis. we should analyse the access patterns and apply this to only to values that flip back and forth a lot. I suspect we don't have a lot of slots like that (the reentrancy guard being the only one, and it's already treated like this)

**Comment by RahulMaganti47** [comment]
yea makes sense -- as far as i can tell, there aren't a lot of slots for which this change will be useful but wanted to flag in explicitly to potentially consider.

**Comment by RahulMaganti47** [comment]
here are two that make use of the flag 


https://github.com/wormhole-foundation/example-native-token-transfers/blob/ebd4984e30f678fc1b0d70e3ba8c31fdaf6002ed/evm/src/Transceiver/WormholeTransceiver/WormholeTransceiverState.sol#L239-L246 

https://github.com/wormhole-foundation/example-native-token-transfers/blob/ebd4984e30f678fc1b0d70e3ba8c31fdaf6002ed/evm/src/Transceiver/WormholeTransceiver/WormholeTransceiverState.sol#L229-L236  

but these are configurations so likely won't change frequently n

**Comment by kcsongor** [comment]
as an aside, this uint256 of boolean is a prime candidate for a user defined value type. Could put into a separate library

**Comment by RahulMaganti47** [comment]
> as an aside, this uint256 of boolean is a prime candidate for a user defined value type. Could put into a separate library

ah yea - good shout, that'll be nice.

**Comment by djb15** [comment]
Closing as no changes planned
