### ISSUE TITLE
solana: Integer overflows in TrimmedAmount decimal scaling 

### ISSUE THREAD

**Issue by johnsaigle** [wormhole-foundation/example-native-token-transfers#266]
`TrimmedAmount::scale` has two potential overflows:

https://github.com/wormhole-foundation/example-native-token-transfers/blob/8936c147c3c4698aa84e016a656c388461f81a35/solana/modules/ntt-messages/src/trimmed_amount.rs#L53-L62

For clarity, I'm adding names to some of these expressions:

```rust
 } else {  // line 59 above
         let difference: u64 = (to_decimals - from_decimals).into();
         let scaling_factor: u64 = 10_u64.pow(difference);
         let product = amount * scaling_factor;
 } 
```

### Scaling Factor exponentiation overflow
(See also https://github.com/wormhole-foundation/example-native-token-transfers/issues/242 for discussion of truncation issues and how the Rust code compares to the Solidity implementation.)

`scaling_factor`, as I've named it above, will overflow when `difference > 18`. This expression is required to be u64, therefore its max value is [u64::MAX](https://doc.rust-lang.org/std/primitive.u64.html#associatedconstant.MAX) which is ~`1.8e19`.

We're dealing only with powers of 10 here. 10e18 is safe but 10e19 is not.

### Overflow occurs when scaling amount
Clearly this value can overflow for very large amounts. If `amount` is near `u64::MAX` then scaling it by even a modest scaling factor will overflow.

Interestingly, this can also occur on the other side of the expression. If `scaling_factor` is large, this limits `amount` significantly. If two peers have very different decimals, the amount must be small. 

e.g. If one chain has 24 decimals and another has 6 decimals, it will create a `scaling_factor` of `10e18` (24 - 6).  Then the only valid amounts are `0` and `1`. Multiplying by any larger (integer) value will overflow because `2 * 10e18 > 1.8e19`.

In a more plausible example, if the two chains have toDecimals == 18 and fromDecimals == 6, then the `scaling_factor` is `10e12`. Then the maximum amount is about 1800000 (`1.8e6`).

### Exponentiation

I think we should throw an error in the function linked above when `difference > 18`. The system can't handle this exponentiation and we might as well document this and throw an error rather than Panic. 

Things are more complicated if we have some sort of weird circumstance in which a chain/token happens to use a very large number of decimals. However, such a chain will be able to only transfer very small amounts. If its decimals are large enough, it will be possible to register the chain but it will not be possible to send any amounts.

Probably this isn't realistic, but perhaps we should be explicit about this in documentation somewhere; it shouldn't be possible to register a chain that has `255` decimals. Registration is an admin function so we don't need to be all that concerned. On the other hand if this is an invalid state for our program, why not enforce that?

### Scaling
As for the relationship between amount and `scaling_factor`, I'm unsure what we should do here. It's an important part of the design to be able to scale the decimals between chains, but it also seems odd to me that the `amount` that can be sent in a transfer is bounded by how dissimilar the chains are in their decimals.

Maybe this is fine? If it is, I think we can add comments, explicit reverts, and unit tests so that we handle overflows defensively rather than relying on Rust to panic (as overflow checks enabled in release). An equivalent of https://github.com/wormhole-foundation/example-native-token-transfers/pull/262 would be a good approach.

**Comment by kcsongor** [comment]
Agree about adding explicit overflow checks here.

Another check we should consider adding is on the sending side, before the transfer is sent, ensuring the recipient will be able to untrim the amount to its desired decimals. The contracts know their peers' decimals, so they could perform this check before sending out. This way, the transaction would revert on the *sending* side, not the *receiving* side in case the target chain wouldn't be able to handle the amount.

**Comment by johnsaigle** [comment]
@kcsongor thanks I'll try out an implementation of error handling and we can refine it in that PR
