### ISSUE TITLE
evm: Discuss chain id validation

### ISSUE THREAD

**Issue by djb15** [wormhole-foundation/example-native-token-transfers#303]
We could/should validate that the chain id we deploy with is actually the Wormhole chain id for that EVM chain. This again raises the question about what the canonical chain id should be (right now WH id is the canonical id).

> Basically chainId from the point of the manager didn't actually need to be a wormhole chain id, but it has ended up being so. For example a different transceiver with a different set of chain ids (e.g. Axelar) would have to map from Wormhole chain id to Axelar chain id in their transceiver logic. I'm not sure exactly how we want to validate chain id here because we don't necessarily want the manager to need to know about Wormhole (since that's transceiver specific). Re publishing, the VAA includes the emitter chain so no need to add the wormhole chain id to the payload.

**Comment by djb15** [comment]
We are going to stick with the WH chain id as the canonical id

**Comment by johnsaigle** [comment]
can we close this issue then?

**Comment by djb15** [comment]
Yeah just keeping this open until the audit contest finishes to make it clear it's a known "issue"

**Comment by djb15** [comment]
Superseded by #353
